name: Use Secret API Key

on: [push]

jobs:
  use-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Use secret API key
        run: echo "Using secret API key: ${{ secrets.API_KEY }}"
        working-directory: Lab\ 1
