name: Use Secret API Key

on: [push]

jobs:
  use-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Change directory to Lab 1
        run: cd "Lab 1"

      - name: Use secret API key
        run: echo "Using secret API key: ${{ secrets.API_KEY }}"
        working-directory: Lab 1
